// <auto-generated />
namespace Garage_2_0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixeddatebugIthink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixeddatebugIthink));
        
        string IMigrationMetadata.Id
        {
            get { return "201706121237106_fixed date bug, I think"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
